### PR TITLE
Remove tests from boilerplate

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

This PR removes the tests + comments from the boilerplate. Should not be merged until https://github.com/freeCodeCamp/freeCodeCamp/pull/40358 lands on production.

### CODE REVIEW

**Review by moT01 — APPROVED** [review]
LGTM 🎉 

Just need the associated PR to hit production

**Review by ShaunSHamilton — APPROVED** [review]
Aside from what I mentioned on the `/learn` changes. If we are ok with that little detail, this LGTM 👍

**Comment by ShaunSHamilton** [comment]
Thanks, for that, Nich.

**Comment by Kenneth-bit** [comment]
Hello, I would like to know if the Imperial Converter is fine and tets well or should I move on to other projects...I am using repl.it and it gives me problems...sometimes the code doesn't use node js at all. Please help...should I use Git instead maybe that will work?

**Comment by ShaunSHamilton** [comment]
@Kenneth-bit Yes, the Metric-Imperial converter should be fine, and is completable. If you are looking for assistance with your project/code, I recommend you open a topic on the [forum](https://forum.freecodecamp.org), and please provide as much information as needed:
- Link to your project
- Relevant code
- Errors you can see in logs/console

> sometimes the code doesn't use node js at all. Please help...should I use Git instead maybe that will work?

I am not sure what you mean by this. What code? Also, Node.js and Git are not comparable - Node.js is a JavaScript Runtime, Git is a Version Control System.

**Comment by Kenneth-bit** [comment]
About your confusion : I am not sure what you mean by this. What code?
Also, Node.js and Git are not comparable - Node.js is a JavaScript Runtime,
Git is a Version Control System.

I understand my confusion, my problem was with my packages, after I
installed nodemon it helped and I saw that my node js is fine and I was
missing a the .env file.

Thank you for your response, I am still new to Open Source so Git is still
a mountain I'm excited to climb during my growth with FreeCodeCamp.

I can't wait to earn my Legacy Certificates

**Comment by RandellDawson** [comment]
@moT01 I believe we can merge this now?

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
