### PR TITLE
Fix convertForm submit

### LINKED ISSUE #15281: Front end doesn't work
Challenge [metricimperial-converter](http://beta.freecodecamp.com/en/challenges/information-security-and-quality-assurance-projects/metricimperial-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.0.12137 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

https://hard-twilight.glitch.me/

Filling in the frontend portion returns nothing whenever the convert button is pressed

### PR DESCRIPTION
**Pull request by user512**
closes https://github.com/freeCodeCamp/freeCodeCamp/issues/15281

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:
- [x] Tested changes locally.

#### Description
User can now click on press enter to submit convertForm

### CODE REVIEW

**Comment by user512** [comment]
@raisedadead, not sure why but I can't trigger the the conversion but I know it's going to the form submit listener when user press enter or click convert button. Let me know if it's my local setup problem, thank you.

**Comment by raisedadead** [comment]
Have you tested this by creating a glitch.com project?

**Comment by user512** [comment]
@raisedadead, thank for reminding me about testing on glitch.com.
Code is tested here https://auspicious-mascara.glitch.me/
And here is the glitch.me code: https://glitch.com/edit/#!/auspicious-mascara

**Review by raisedadead — APPROVED** [review]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @user512

**Comment by raisedadead** [comment]
@JosephLivengood Please merge and deploy.

**Comment by QuincyLarson** [comment]
LGTM!

**Pull request merged**
